@NamespaceAccessible
public class ExtoleConstants {
    public static final String BASE_URL                  = 'https://api.extole.io';
    public static final String EVENTS_PATH               = '/v5/events';
    public static final String PEOPLE_PATH               = '/v5/persons';
    public static final String REWARDS_PATH              = '/rewards';
    public static final String CAMPAIGNS_SUMMARY_PATH    = '/v2/campaign-summaries';
    public static final String CAMPAIGNS_PATH            = '/v2/campaigns';
    public static final String REPORT_RUNNERS_PATH       = '/v7/report-runners';
    public static final String REPORT_V4_PATH            = '/v4/reports';
    public static final String REPORT_DOWNLOAD_PATH      = '/download.json';
    public static final String AUDIENCES_PATH            = '/v1/audiences';
    public static final String ZONES_PATH                = '/v5/zones';
}
